import type { Metadata } from "next";
import {
  Russo_One
} from "next/font/google";
import "./globals.css";
import ApolloProviderComponent from "@/lib/apollo-provider";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

const font = Russo_One
  ({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ApolloProviderComponent>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <main className="pt-16">
              {children}

            </main>
          </ThemeProvider>

        </ApolloProviderComponent>
      </body>
    </html>
  );
}
